# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: "acr_pinport"
  imageRepository: 'golangtesting'
  containerRegistry: 'pinport.azurecr.io'
  dockerfilepath: '$(Build.SourcesDirectory)/Azure/VirtualMachine/Dockerfile'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
#        repository: $(imageRepository)
#        containerRegistry: $(dockerRegistryServiceConnection)
        dockerfile: $(dockerfilepath)
        tags: |
          $(tag)


