# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


resources:  
 - repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: "acr_pinport"
  imageRepository: 'golangtesting2'
  containerRegistry: 'pinport.azurecr.io'
  dockerfilepath: '$(Build.SourcesDirectory)/Azure/VirtualMachine/Dockerfile'
  ARM_SUBSCRIPTION_ID: '206c6b04-b170-42cf-ab78-0703dbd83bdc'
  ARM_CLIENT_ID: '4b565304-99d0-4d41-8759-4b995e042f43'
  ARM_TENANT_ID: '7f429a9a-bd6a-4c3d-ac35-a100bd4644c8'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        dockerfile: $(dockerfilepath)
        tags: |
          $(tag)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
            mkdir ./test_output
            docker run \
              -e ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID) \
              -e ARM_CLIENT_ID=$(ARM_CLIENT_ID) \
              -e ARM_CLIENT_SECRET=$(clientsecret) \
              -e ARM_TENANT_ID=$(ARM_TENANT_ID) \
              -v $(System.DefaultWorkingDirectory)/test_output:/go/src/windowsvm/test_output \
              $(containerRegistry)/$(imageRepository):$(tag)
      displayName: Run tests in container
      env:
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(clientsecret)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
        testResultsFiles: '**/report.xml'
        failTaskOnFailedTests: true